<?php
namespace backend\assets;

use yii\web\AssetBundle;
use yii\web\View;


class AdminLTEAsset extends AssetBundle
{
    public $sourcePath = '@vendor/';
    public $js = [
    ];

    public $css = [
        'almasaeed2010/adminlte/dist/css/AdminLTE.css',
        'almasaeed2010/adminlte/dist/css/skins/_all-skins.min.css',
        'almasaeed2010/adminlte/bower_components/font-awesome/css/font-awesome.css',
        'almasaeed2010/adminlte/bower_components/Ionicons/css/ionicons.css',

        'kartik-v/yii2-widget-select2/src/assets/css/select2-addl.css',
        'kartik-v/yii2-widget-select2/src/assets/css/select2-krajee.css',
    ];
    public $depends = [
        'dmstr\web\AdminLteAsset',
        'backend\assets\AppAsset',
    ];

    public function init()
    {
        $this->cssOptions['position'] = View::POS_HEAD;
        parent::init(); // TODO: Change the autogenerated stub
    }


}